### PR TITLE
Parsing country output fix

### PR DESCRIPTION
**Pull request by ReveHavan**
Added support for nordvpn 3.18.3

### CODE REVIEW

**Comment by Isopolito** [comment]
Hi @ReveHavan , thanks for contributing. I'll test this out as soon as I get some free time and merge it in if everything looks good.

**Comment by Isopolito** [comment]
Hi @ReveHavan, I'm testing things now. Can you send me some examples of the output that was breaking the cities/country logic that your code fixes. I'd like to play with it a bit locally

**Comment by ReveHavan** [comment]
Hi @Isopolito, this is the raw output from "nordvpn countries" command.
```
Albania                            [94mAlgeria[0m                            [94mAndorra[0m                            [94mArgentina[0m                          [94mArmenia[0m
Australia                          Austria                            [94mAzerbaijan[0m                         [94mBahamas[0m                            [94mBangladesh[0m
Belgium                            [94mBelize[0m                             [94mBermuda[0m                            [94mBhutan[0m                             [94mBolivia[0m
Bosnia_And_Herzegovina             Brazil                             [94mBrunei_Darussalam[0m                  Bulgaria                           [94mCambodia[0m
Canada                             [94mCayman_Islands[0m                     Chile                              Colombia                           [94mCosta_Rica[0m
Croatia                            Cyprus                             Czech_Republic                     Denmark                            [94mDominican_Republic[0m
[94mEcuador[0m                            [94mEgypt[0m                              [94mEl_Salvador[0m                        Estonia                            Finland
France                             Georgia                            Germany                            [94mGhana[0m                              Greece
[94mGreenland[0m                          [94mGuam[0m                               [94mGuatemala[0m                          [94mHonduras[0m                           Hong_Kong
Hungary                            Iceland                            [94mIndia[0m                              Indonesia                          Ireland
[94mIsle_Of_Man[0m                        Israel                             Italy                              [94mJamaica[0m                            Japan
[94mJersey[0m                             [94mKazakhstan[0m                         [94mKenya[0m                              [94mLao_Peoples_Democratic_Republic[0m    Latvia
[94mLebanon[0m                            [94mLiechtenstein[0m                      Lithuania                          Luxembourg                         Malaysia
[94mMalta[0m                              Mexico                             Moldova                            [94mMonaco[0m                             [94mMongolia[0m
[94mMontenegro[0m                         [94mMorocco[0m                            [94mMyanmar[0m                            [94mNepal[0m                              Netherlands
New_Zealand                        [94mNigeria[0m                            North_Macedonia                    Norway                             [94mPakistan[0m
[94mPanama[0m                             [94mPapua_New_Guinea[0m                   [94mParaguay[0m                           [94mPeru[0m                               [94mPhilippines[0m
Poland                             Portugal                           [94mPuerto_Rico[0m                        Romania                            Serbia
Singapore                          Slovakia                           Slovenia                           South_Africa                       South_Korea
Spain                              [94mSri_Lanka[0m                          Sweden                             Switzerland                        Taiwan
[94mThailand[0m                           [94mTrinidad_And_Tobago[0m                Turkey                             Ukraine                            United_Arab_Emirates
United_Kingdom                     United_States                      [94mUruguay[0m                            [94mUzbekistan[0m                         [94mVenezuela[0m
[94mVietnam[0m

[94m* Virtual location servers[0m
```

**Comment by Isopolito** [comment]
got it @ReveHavan , thanks!

**Pull request merged**
